baseURL = "https://mattiariccadonna.com/"
languageCode = "it"
title = "Mattia Riccadonna"
theme = "nostyleplease"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    style = 'rrt'
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  description = "Pittore, acquerellista, illustratore. Archivio di opere dal 2002 ad oggi."
  keywords = ["arte", "pittura", "acquerello", "illustrazione", "Mattia Riccadonna", "Trentino"]

  [params.theme_config]
    appearance        = "auto"       # "light", "dark", "auto"
    back_home_text    = "← indietro"
    date_format       = "2006-01-02"
    isListGroupByDate = true
    isShowFooter      = true
    show_description  = true         # mostra la descrizione sotto il titolo in home

[sitemap]
  changefreq = "weekly"
  priority   = 0.5
  filename   = "sitemap.xml"
