baseURL = "https://mattiariccadonna.com/"
languageCode = "it"
title = "Mattia Riccadonna"
theme = "typo"

# Google analytics code
#googleAnalytics = "G-CJZF9EPTD0"

[taxonomies]
tag = "tags"

[params]
description = "Galleria personale, idee e dipinti di Mattia Riccadonna"
keywords = ["arte contemporanea", "galleria d'arte", "pittura ad olio", "artista italiano", "Mattia Riccadonna", "paesaggi del Trentino-Alto Adige"]
subtitle = "Colori e luce"

# Appearance settings
theme = 'light'
colorPalette = 'eink'
hideHeader = false

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

# Social icons
[[params.social]]
name = "Reddit"
url = "https://www.reddit.com/user/mattia_riccadonna/"

[[params.social]]
name = "Instagram"
url = "https://www.instagram.com/mattiariccadonna/"

#[[params.social]]
#name = "facebook"
#url = "https://www.facebook.com/mattia.riccadonna86"

#[[params.social]]
#name = "Whatsapp"
#url = "https://wa.me/393200866982"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "galleria"
url = "/galleria"

#[[params.menu]]
#name = "posts"
#url = "/posts"

[[params.menu]]
name = "contatti"
url = "/contatti"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[params.umami]
enable = true
websiteId = "7f1594c8-ae9f-4d1d-96dc-05f5c62de636"
jsLocation = "https://cloud.umami.is/script.js"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
